### ISSUE TITLE
Overlay xrfclk issue

### ISSUE THREAD

**Issue by JaredHermans** [strath-sdr/rfsoc_ofdm#13]
I followed the exact instructions to run the ofdm demonstration on the zcu111; flashed PYNQ 2.7 and ran pip3 install git+https://github.com/strath-sdr/rfsoc_ofdm

However, as soon as the overlay is loaded there is an issue:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-ee74b19f5b94> in <module>
      2 import ipywidgets as ipw
      3 
----> 4 ofdm_hw = Overlay()

/usr/local/share/pynq-venv/lib/python3.8/site-packages/rfsoc_ofdm-0.3.2-py3.8.egg/rfsoc_ofdm/overlay.py in __init__(self, bitfile_name, init_rf_clks, **kwargs)
     27         self.adc_block = self.adc_tile.blocks[0]
     28 
---> 29         self.configure_clocks()
     30         self.configure_adcs()
     31         self.configure_dacs()

/usr/local/share/pynq-venv/lib/python3.8/site-packages/rfsoc_ofdm-0.3.2-py3.8.egg/rfsoc_ofdm/overlay.py in configure_clocks(self, lmk_freq, lmx_freq)
     53         """
     54 
---> 55         xrfclk.set_ref_clks(lmk_freq=lmk_freq, lmx_freq=lmx_freq)
     56 
     57 

/usr/local/share/pynq-venv/lib/python3.8/site-packages/xrfclk/xrfclk.py in set_ref_clks(lmk_freq, lmx_freq)
    248 
    249     for lmk in lmk_devices:
--> 250         _set_LMK_clks(lmk_freq, lmk)
    251     for lmx in lmx_devices:
    252         _set_LMX_clks(lmx_freq, lmx)

/usr/local/share/pynq-venv/lib/python3.8/site-packages/xrfclk/xrfclk.py in _set_LMK_clks(lmk_freq, lmk)
    153         raise RuntimeError("Frequency {} MHz is not valid.".format(lmk_freq))
    154     else:
--> 155         _write_LMK_regs(_Config[lmk['compatible']][lmk_freq], lmk)
    156 
    157 def _get_spidev_path(dev):

/usr/local/share/pynq-venv/lib/python3.8/site-packages/xrfclk/xrfclk.py in _write_LMK_regs(reg_vals, lmk)
     73                 f.write(data[1:])
     74             else:
---> 75                 f.write(data)
     76 
     77 def _write_LMX_regs(reg_vals, lmx):

OSError: [Errno 6] No such device or address

Any ideas on how to solve this error?

**Comment by dnorthcote** [comment]
Hi @JaredHermans, 

We were unable to reproduce your issue with our ZCU111 board.

Have you tried using other PYNQ examples on your board or any off-the-shelf Xilinx examples such as RFDC Evaluation.

My first thought is that there is something wrong with your board. In particular, xrfclk can't find your LMX clock chip,

Thanks,
David.

**Comment by dnorthcote** [comment]
Hi @JaredHermans, 

Do you have any further updates here?

Thanks,
David.

**Comment by dnorthcote** [comment]
Close due to no reply.

**Comment by dnorthcote** [comment]
Close due to no reply.

**Comment by dnorthcote** [comment]
Close due to no reply.
