### ISSUE TITLE
Clean up the transmit and receive hierarchies

### ISSUE THREAD

**Issue by dnorthcote** [strath-sdr/rfsoc_ofdm#2]
We should add the following hierarchy to allow this overlay to be compatible with drivers from rfsoc_sam.

The IPI diagram needs the following hierarchies:

radio -> receiver -> channel_yx -> (ofdm ip cores)
radio -> transmitter -> channel_yx -> (ofdm ip cores)
radio -> rfdc (ip core)

y is the tile, and x is the block.
The IP Cores in the channel hierarchies can be linked using a software wrapper.

See the hierarchies.py and channels.py in rfsoc_sam_private for an idea of whats happening here.

**Comment by axdy** [comment]
No longer progressing.
